### PR TITLE
chore: Bump versions and restructure folder

### PR DESCRIPTION
**Pull request by miurahr**
This is a proposal to bump versions of tools, and restructure of folders.
When using Apache-FOP 2.9, we need to copy fop-hypen.jar from another place.

- Ubuntu 22.04
- fop@2.9
- whc@3.5.1

It also fix the bug that fop failed with "File Not Found" error for ".fop" directory. A ".fop" directory is cache folder when Apache-FOP working.
To fix the bug, doing
1. change user from nobody (no write access) to new user omegat 
2. make .fop folder on omegat home directory.

### CODE REVIEW

**Comment by brandelune** [comment]
Can we also increase the DocBook version? The official version is 5.1. There are some things that would be easier to do with 5.1 compared to 4.5.

**Comment by miurahr** [comment]
> Can we also increase the DocBook version? The official version is 5.1. There are some things that would be easier to do with 5.1 compared to 4.5.

I would like to follow the documentation team decision.

**Comment by brandelune** [comment]
> > Can we also increase the DocBook version? The official version is 5.1. There are some things that would be easier to do with 5.1 compared to 4.5.
> 
> I would like to follow the documentation team decision.

@Kazephil would you have objections against moving to DocBook 5.1?

I'm currently checking with the DocBook user group for a list of changes between 4.5 and 5.1. I seem to remember that 5.1 allows a more modular style of authoring.

**Comment by Kazephil** [comment]
> @Kazephil would you have objections against moving to DocBook 5.1?

None whatsoever. That was actually something I wanted to look into. (Along with modernizing the rest of the toolchain.)

The only concern might be the DocBook filter. Does it support DocBook 5.1?
(The Okapi XML filter seems to support DocBook 5 through one of its configurations, but it would be nice to support it "natively" in OmegaT for the localisation of the manual without requiring the installation of a third-party plugin.)

> I'm currently checking with the DocBook user group for a list of changes between 4.5 and 5.1. I seem to remember that 5.1 allows a more modular style of authoring.

I did a quick search this morning, and that seems to be the main change in 5.x. It adds the `topic` element and the `assembly` structure to enable more modular writing, and that looks pretty appealing to me.

It fits in well with some ideas on reorganizing or restructuring the documentation that I want to get around to fleshing out.

**Comment by miurahr** [comment]
I've pushed successor PR #4  that reduce container size significantly. It drop support for PDF generation in default.

**Comment by miurahr** [comment]
Ubuntu distributed[ docbook-xml package version 4.5-11](https://packages.ubuntu.com/jammy/docbook-xml)

**Comment by miurahr** [comment]
Most recent docbook stylesheet is https://github.com/docbook/xslTNG

@Kazephil @brandelune When you find a way how to install it for OmegaT project, please tell me. I may be able to help to update  container image.

**Comment by brandelune** [comment]
> Ubuntu distributed[ docbook-xml package version 4.5-11](https://packages.ubuntu.com/jammy/docbook-xml)

I'm surprised they don't have DocBook 5.1. Is it a limitation of the Ubuntu version?

**Comment by miurahr** [comment]
> > Ubuntu distributed[ docbook-xml package version 4.5-11](https://packages.ubuntu.com/jammy/docbook-xml)
> 
> I'm surprised they don't have DocBook 5.1. Is it a limitation of the Ubuntu version?

No, same for debian  alpine linux.

**Comment by brandelune** [comment]
> Most recent docbook stylesheet is https://github.com/docbook/xslTNG
> 
> @Kazephil @brandelune When you find a way how to install it for OmegaT project, please tell me. I may be able to help to update container image.

Thank you for checking. I'll be asking the DocBook group.

**Comment by miurahr** [comment]
There is https://packages.ubuntu.com/jammy/docbook5-xml and https://packages.ubuntu.com/jammy/docbook-xsl-ns package

**Comment by miurahr** [comment]
Size  577.9 MiB   blob 198.5 MiB here
When your concern is a size  of container, I would like to recommend to adopt #4

**Comment by miurahr** [comment]
Please see #4

**Pull request closed without merging**
